apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app
resources:
- serviceaccount.yaml
- rbac.yaml
- deployment.yaml
configMapGenerator:
- name: my-app
  files:
  - config/run.sh
