apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-app
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - my-app
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-app
subjects:
- kind: ServiceAccount
  name: my-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-app
